import spotifyAxios from "./spotifyAxios.js";
import pLimit from "p-limit";
import spotifyPreviewFinder from "spotify-preview-finder";
import dotenv from "dotenv"
async function searchTrack(song, artist, token) {
  try {
    const query = encodeURIComponent(`${song} ${artist}`);
    const url = `https://itunes.apple.com/search?term=${query}&entity=song&limit=1`;
    const res1 = await fetch(url);
    const data1 = await res1.json();
    const res = await spotifyAxios.get(
      `/v1/search?q=${query}&type=track&limit=1`,
      { headers: { Authorization: `Bearer ${token}` } }
    );
    //Get the first track in search results
    const track = res.data.tracks.items[0];
    //console.log("Track: ", track);
    if (!track) return null; // no results

    //const previewUrl = await spotifyPreviewFinder(`${song}`, `${artist}`, 2);
    //console.log("PreviewObject: ", previewUrl.results[0].previewUrls);
    return {
      title: track.name,
      artist: track.artists.map((a) => a.name).join(", "),
      album: track.album.name,
      uri: track.uri, // "spotify:track:xxxx"
      id: track.id,
      image: track.album.images?.[0]?.url || null,
      duration: track.duration_ms,
      // preview: previewUrl.results[0].previewUrls[0] ?? null
      preview: data1.results[0].previewUrl
    };
  } catch (err) {
    console.log(`No match for ${song} by ${artist}`);
    return [];
  }
}

async function addTrackToArray(user, playlist) {
  const limit = pLimit(5); // max 5 concurrent searches
  const searchPromises = playlist.map((item) =>
    limit(() => searchTrack(item.title, item.artist, user.accessToken))
  );

  // wait for all results
  const results = await Promise.all(searchPromises);

  // filter out nulls (failed searches)
  const validTracks = results.filter((track) => track !== null);
  return validTracks;


}

async function createPlaylist(userId, name, token) {
  const res = await spotifyAxios.post(
    `/v1/users/${userId}/playlists`,
    {
      name: name, // Playlist name
      public: false, // true = public, false = private
      description: "Generated by AltoAI",
    },
    {
      headers: { Authorization: `Bearer ${token}` },
    }
  );
  return res.data.id; // Returns the new playlist ID
}

async function addAllTracksToPlaylist(trackURIs, token) {
  try {
    // Step 1: get current user profile to find userId
    const userRes = await spotifyAxios.get("/v1/me", {
      headers: { Authorization: `Bearer ${token}` },
    });
    const userId = userRes.data.id;

    // Step 2: create a new playlist
    const playlistId = await createPlaylist(userId, "Alto-AI", token);

    // Step 3: add all tracks from array
    const addRes = await spotifyAxios.post(
      `/v1/playlists/${playlistId}/tracks`,
      { uris: trackURIs },
      { headers: { Authorization: `Bearer ${token}` } }
    );

    console.log("Tracks added:", addRes.status === 201 ? "✅" : "❌");
  } catch (err) {
    console.error(
      "Error creating playlist or adding tracks:",
      err.response?.data || err.message
    );
  }
}

export async function checkValidSongs(user, playlist) {
  const tracks = await addTrackToArray(user, playlist);
  if (tracks.length > 0) {
    const trackURIs = tracks.map((track) => track.uri);
    //await addAllTracksToPlaylist(trackURIs, user.accessToken);
  } else {
    console.log("⚠️ No valid tracks found.");
  }
  
  return tracks;
}
