import axios from "axios";
import pLimit from "p-limit";
import { getAccessToken } from "./spotifyAuth.js";

async function searchTrack(song, artist, token) {
  const query = encodeURIComponent(`${song} ${artist}`);
  const res = await axios.get(
    `https://api.spotify.com/v1/search?q=${query}&type=track&limit=1`,
    { headers: { Authorization: `Bearer ${token}` } }
  );

  if (res.data.tracks.items.length > 0) {
    return res.data.tracks.items[0].uri; // e.g. "spotify:track:6habFhsOp2NvshLv26DqMb"
  } else {
    console.log(`No match for ${song} by ${artist}`);
    return null;
  }
}

async function createPlaylist(userId, name, token) {
  const res = await axios.post(
    `https://api.spotify.com/v1/users/${userId}/playlists`,
    {
      name: name, // Playlist name
      public: false, // true = public, false = private
      description: "Generated by my app",
    },
    {
      headers: { Authorization: `Bearer ${token}` },
    }
  );
  return res.data.id; // Returns the new playlist ID
}

async function addOneTracksToPlaylist(trackURIs, token) {
  try {
    // Step 1: get current user profile to find userId
    const userRes = await axios.get("https://api.spotify.com/v1/me", {
      headers: { Authorization: `Bearer ${token}` },
    });
    const userId = userRes.data.id;

    // Step 2: create a new playlist
    const playlistId = await createPlaylist(userId, "Alto-AI", token);

    // Step 3: add tracks
    const addRes = await axios.post(
      `https://api.spotify.com/v1/playlists/${playlistId}/tracks`,
      { uris: trackURIs },
      { headers: { Authorization: `Bearer ${token}` } }
    );

    console.log("Tracks added:", addRes.status === 201 ? "✅" : "❌");
  } catch (err) {
    console.error(
      "Error creating playlist or adding tracks:",
      err.response?.data || err.message
    );
  }
}

export async function addAllSongsToPlaylist(playlist) {
  if (!global.SPOTIFY_REFRESH_TOKEN) {
    console.log("No refresh token available. Login first!");
    return;
  }
  const token = await getAccessToken(global.SPOTIFY_REFRESH_TOKEN);
  const songs = playlist;
  console.log("Playlist: ", songs);
  const limit = pLimit(5); // max 5 concurrent searches
  // const trackURIs = [];
  // for (const item of songs) {
  //   const uri = await searchTrack(item["title"], item.artist, token);
  //   if (uri) trackURIs.push(uri);
  // }
  const searchPromises = playlist.map((item) =>
    limit(() => searchTrack(item.title, item.artist, token))
  );
  // Wait for all searches, filtering out nulls
  const trackURIs = (await Promise.all(searchPromises)).filter(
    (uri) => uri !== null
  );
  if (trackURIs.length > 0) {
    await addOneTracksToPlaylist(trackURIs, token);
  } else {
    console.log("No valid tracks found.");
  }
}
