import axios from "axios";
import pLimit from "p-limit";
import { getAccessToken } from "./spotifyAuth.js";

async function searchTrack(song, artist, token) {
  try {
    const query = encodeURIComponent(`${song} ${artist}`);
    const res = await axios.get(
      `https://api.spotify.com/v1/search?q=${query}&type=track&limit=1`,
      { headers: { Authorization: `Bearer ${token}` } }
    );
    //Get the first track in search results
    const track = res.data.tracks.items[0];
    if (!track) return null; // no results
    return {
      title: track.name,
      artist: track.artists.map((a) => a.name).join(", "),
      album: track.album.name,
      uri: track.uri, // "spotify:track:xxxx"
      id: track.id,
      image: track.album.images?.[0]?.url || null,
    };
  } catch (err) {
    console.log(`No match for ${song} by ${artist}`);
    return [];
  }
}

async function addTrackToArray(playlist, token) {
  const limit = pLimit(5); // max 5 concurrent searches
  const searchPromises = playlist.map((item) =>
    limit(() => searchTrack(item.title, item.artist, token))
  );

  // wait for all results
  const results = await Promise.all(searchPromises);

  // filter out nulls (failed searches)
  const validTracks = results.filter((track) => track !== null);
  return validTracks;
}

async function createPlaylist(userId, name, token) {
  const res = await axios.post(
    `https://api.spotify.com/v1/users/${userId}/playlists`,
    {
      name: name, // Playlist name
      public: false, // true = public, false = private
      description: "Generated by my app",
    },
    {
      headers: { Authorization: `Bearer ${token}` },
    }
  );
  return res.data.id; // Returns the new playlist ID
}

async function addAllTracksToPlaylist(trackURIs, token) {
  try {
    // Step 1: get current user profile to find userId
    const userRes = await axios.get("https://api.spotify.com/v1/me", {
      headers: { Authorization: `Bearer ${token}` },
    });
    const userId = userRes.data.id;

    // Step 2: create a new playlist
    const playlistId = await createPlaylist(userId, "Alto-AI", token);

    // Step 3: add all tracks from array
    const addRes = await axios.post(
      `https://api.spotify.com/v1/playlists/${playlistId}/tracks`,
      { uris: trackURIs },
      { headers: { Authorization: `Bearer ${token}` } }
    );

    console.log("Tracks added:", addRes.status === 201 ? "✅" : "❌");
  } catch (err) {
    console.error(
      "Error creating playlist or adding tracks:",
      err.response?.data || err.message
    );
  }
}

export async function checkValidSongs(playlist) {
  if (!global.SPOTIFY_REFRESH_TOKEN) {
    console.log("No refresh token available. Login first!");
    return;
  }
  const token = await getAccessToken(global.SPOTIFY_REFRESH_TOKEN);

  const tracks = await addTrackToArray(playlist, token);
  if (tracks.length > 0) {
    const trackURIs = tracks.map((track) => track.uri);
    await addAllTracksToPlaylist(trackURIs, token);
  } else {
    console.log("⚠️ No valid tracks found.");
  }
}
